spring:
  application:
    name: knowledge-base-bulid

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/knowledge_base_rebuild}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


server:
  port: 8082


app:
  chunk:
    max-chars: 500
    overlap-chars: 50